import type { Fact } from "../types";

/**
 * BELSŐ adatnyilvántartás — nem publikus és ismeretlen adatok.
 * Publikus kód nem importálhatja (teszt és verify:public ellenőrzi).
 */
export const INTERNAL_FACTS = [
  {
    id: "price-history",
    label: "Korábbi nyilvános kínálati árak",
    value: "1,2 millió EUR (korábbi adat); közvetítői hirdetésekben 1,25 millió EUR, majd 990 000 EUR",
    status: "nyilvanos-megerositendo",
    source: "SRC-BROKER",
    visibility: "hidden",
    note: "F-040–F-044. Nem jóváhagyott aktuális irányár; nem publikálható (D-003).",
  },
  {
    id: "floor-area",
    label: "Beépített terület",
    value: "„over 2,000 m²”",
    status: "nyilvanos-megerositendo",
    source: "SRC-BROKER",
    visibility: "internal",
    note: "F-015: egyetlen közvetítő háromszor ismételt állítása; alaprajz kell.",
  },
  {
    id: "plot-area",
    label: "Telekméret",
    value: "5 000 m²",
    status: "nyilvanos-megerositendo",
    source: "SRC-BROKER",
    visibility: "internal",
    note: "F-016: egyetlen hirdetés; tulajdoni lap kell.",
  },
  {
    id: "build-year",
    label: "Építési év",
    value: "Ellentmondó: 1830 / 1900 / 1911-es átépítés",
    status: "ismeretlen",
    source: "SRC-HVH-WEB",
    visibility: "internal",
    note: "F-010–F-012 ütköznek; a publikus oldalon egyeztetési témaként szerepel, szám nélkül.",
  },
  {
    id: "legal-operator",
    label: "Üzemeltető jogi név",
    value: "Gasthof Borok OG (kontaktoldal)",
    status: "nyilvanos-megerositendo",
    source: "SRC-HVH-WEB",
    visibility: "internal",
    note: "F-003; cégnyilvántartási ellenőrzés szükséges.",
  },
  {
    id: "broker",
    label: "Külső közvetítő",
    value: "Nem kizárólagos, általános megbízású közvetítő hirdeti",
    status: "nyilvanos-megerositendo",
    source: "SRC-BROKER",
    visibility: "internal",
    note: "F-042, F-045; jogosultság tisztázandó (R-01).",
  },
  {
    id: "yield",
    label: "Hozam, pénzügyi eredmény",
    value: null,
    status: "ismeretlen",
    source: "SRC-BRIEF-0930",
    visibility: "hidden",
  },
  {
    id: "condition",
    label: "Állapotminősítés",
    value: null,
    status: "ismeretlen",
    source: "SRC-BRIEF-0930",
    visibility: "hidden",
    note: "A közvetítő „excellent condition” állítása műszaki dokumentum nélkül nem vehető át (F-046).",
  },
  {
    id: "renovation-cost",
    label: "Felújítási költség",
    value: null,
    status: "ismeretlen",
    source: "SRC-BRIEF-0930",
    visibility: "hidden",
  },
  {
    id: "permits",
    label: "Magánhasználati vagy átalakítási engedély",
    value: null,
    status: "ismeretlen",
    source: "SRC-BRIEF-0930",
    visibility: "hidden",
  },
  {
    id: "documents",
    label: "Működési, műszaki és jogi dokumentáció",
    value: "Hiányos",
    status: "jovahagyott",
    source: "SRC-BRIEF-0930",
    visibility: "internal",
  },
] as const satisfies readonly Fact[];
